---

- name: "Set default ip address for zabbix_agent_ip"
  set_fact:
    zabbix_agent_ip: "{{ hostvars[inventory_hostname]['ansible_ip_addresses'][0] }}"
  when:
    - zabbix_agent_ip is not defined
    - "'ansible_ip_addresses' in hostvars[inventory_hostname]"

- name: "Windows | Place TLS-PSK file"
  ansible.windows.win_copy:
    content: "{{ zabbix_agent_tlspsk_secret }}"
    dest: "{{ zabbix_agent_tlspskfile }}"
  when:
    - zabbix_agent_tlspskfile is defined
    - zabbix_agent_tlspsk_secret is defined
  notify: restart win zabbix agent

- name: "Windows | Place TLS-PSK file for agent2"
  ansible.windows.win_copy:
    content: "{{ zabbix_agent2_tlspsk_secret }}"
    dest: "{{ zabbix_agent2_tlspskfile }}"
  when:
    - zabbix_agent2_tlspskfile is defined
    - zabbix_agent2_tlspsk_secret is defined
  notify: restart win zabbix agent

- name: "Windows | Configure zabbix-agent"
  ansible.windows.win_template:
    src: "{{ zabbix_win_config_name }}.j2"
    dest: "{{ zabbix_win_install_dir }}\\{{ zabbix_win_config_name }}"
  notify: restart win zabbix agent

- name: "Windows | Check firewall service"
  ansible.windows.win_service_info:
    name: MpsSvc
  register: firewall_info
  when: zabbix_win_firewall_management

- name: "Windows | Firewall rule"
  community.windows.win_firewall_rule:
    name: "{{ zabbix_win_svc_name }}"
    localport: "{{ zabbix_agent_listenport }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when:
    - zabbix_win_firewall_management
    - firewall_info.services[0].state == 'started' or firewall_info.services[0].start_mode == 'auto'
